language: java
jdk:
    - openjdk8
script:
    - ./mvnw -f nymb-module-parent/pom.xml clean install
    - ./mvnw -f nymb-core/pom.xml clean install
    - ./mvnw -f nymb-parent/pom.xml clean install
notifications:
    email: false
